name: example

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, beta]
  schedule:
    # run daily at 00:00
    - cron: 0 0 * * *

jobs:
  examples:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [24]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run example
